// ======================================================================
// \title  AnalogReadPortAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for AnalogRead port
// ======================================================================

#include "Arduino/Drv/AnalogDriver/AnalogReadPortAc.hpp"
#include "Fw/Types/Assert.hpp"
#include "Fw/Types/ExternalString.hpp"

namespace Drv {

  // ----------------------------------------------------------------------
  // Input Port Member functions
  // ----------------------------------------------------------------------

  InputAnalogReadPort ::
    InputAnalogReadPort() :
      Fw::InputPortBase(),
      m_func(nullptr)
  {

  }

  void InputAnalogReadPort ::
    init()
  {
    Fw::InputPortBase::init();
  }

  void InputAnalogReadPort ::
    addCallComp(
        Fw::PassiveComponentBase* callComp,
        CompFuncPtr funcPtr
    )
  {
    FW_ASSERT(callComp != nullptr);
    FW_ASSERT(funcPtr != nullptr);

    this->m_comp = callComp;
    this->m_func = funcPtr;
    this->m_connObj = callComp;
  }

  Fw::Success InputAnalogReadPort ::
    invoke(U16& val)
  {
#if FW_PORT_TRACING == 1
    this->trace();
#endif

    FW_ASSERT(this->m_comp != nullptr);
    FW_ASSERT(this->m_func != nullptr);

    return this->m_func(this->m_comp, this->m_portNum, val);
  }

#if FW_PORT_SERIALIZATION == 1

  Fw::SerializeStatus InputAnalogReadPort ::
    invokeSerial(Fw::SerializeBufferBase& _buffer)
  {
    // For ports with a return type, invokeSerial is not used
    (void) _buffer;

    FW_ASSERT(0);
    return Fw::FW_SERIALIZE_OK;
  }

#endif

  // ----------------------------------------------------------------------
  // Output Port Member functions
  // ----------------------------------------------------------------------

  OutputAnalogReadPort ::
    OutputAnalogReadPort() :
      Fw::OutputPortBase(),
      m_port(nullptr)
  {

  }

  void OutputAnalogReadPort ::
    init()
  {
    Fw::OutputPortBase::init();
  }

  void OutputAnalogReadPort ::
    addCallPort(InputAnalogReadPort* callPort)
  {
    FW_ASSERT(callPort != nullptr);

    this->m_port = callPort;
    this->m_connObj = callPort;

#if FW_PORT_SERIALIZATION == 1
    this->m_serPort = nullptr;
#endif
  }

  Fw::Success OutputAnalogReadPort ::
    invoke(U16& val) const
  {
#if FW_PORT_TRACING == 1
    this->trace();
#endif

    FW_ASSERT(this->m_port != nullptr);
    return this->m_port->invoke(val);
  }

}
