// ======================================================================
// \title  AnalogDriverComponentAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for AnalogDriver component base class
// ======================================================================

#include "Arduino/Drv/AnalogDriver/AnalogDriverComponentAc.hpp"
#include "Fw/Types/Assert.hpp"
#include "Fw/Types/ExternalString.hpp"
#if FW_ENABLE_TEXT_LOGGING
#include "Fw/Types/String.hpp"
#endif

namespace Arduino {

  // ----------------------------------------------------------------------
  // Component initialization
  // ----------------------------------------------------------------------

  void AnalogDriverComponentBase ::
    init(FwEnumStoreType instance)
  {
    // Initialize base class
    Fw::PassiveComponentBase::init(instance);

    // Connect input port readAnalog
    for (
      FwIndexType port = 0;
      port < static_cast<FwIndexType>(this->getNum_readAnalog_InputPorts());
      port++
    ) {
      this->m_readAnalog_InputPort[port].init();
      this->m_readAnalog_InputPort[port].addCallComp(
        this,
        m_p_readAnalog_in
      );
      this->m_readAnalog_InputPort[port].setPortNum(port);

#if FW_OBJECT_NAMES == 1
      Fw::ObjectName portName;
      portName.format(
        "%s_readAnalog_InputPort[%" PRI_PlatformIntType "]",
        this->m_objName.toChar(),
        port
      );
      this->m_readAnalog_InputPort[port].setObjName(portName.toChar());
#endif
    }

    // Connect input port setAnalog
    for (
      FwIndexType port = 0;
      port < static_cast<FwIndexType>(this->getNum_setAnalog_InputPorts());
      port++
    ) {
      this->m_setAnalog_InputPort[port].init();
      this->m_setAnalog_InputPort[port].addCallComp(
        this,
        m_p_setAnalog_in
      );
      this->m_setAnalog_InputPort[port].setPortNum(port);

#if FW_OBJECT_NAMES == 1
      Fw::ObjectName portName;
      portName.format(
        "%s_setAnalog_InputPort[%" PRI_PlatformIntType "]",
        this->m_objName.toChar(),
        port
      );
      this->m_setAnalog_InputPort[port].setObjName(portName.toChar());
#endif
    }
  }

  // ----------------------------------------------------------------------
  // Getters for typed input ports
  // ----------------------------------------------------------------------

  Drv::InputAnalogReadPort* AnalogDriverComponentBase ::
    get_readAnalog_InputPort(FwIndexType portNum)
  {
    FW_ASSERT(
      portNum < this->getNum_readAnalog_InputPorts(),
      static_cast<FwAssertArgType>(portNum)
    );

    return &this->m_readAnalog_InputPort[portNum];
  }

  Drv::InputAnalogWritePort* AnalogDriverComponentBase ::
    get_setAnalog_InputPort(FwIndexType portNum)
  {
    FW_ASSERT(
      portNum < this->getNum_setAnalog_InputPorts(),
      static_cast<FwAssertArgType>(portNum)
    );

    return &this->m_setAnalog_InputPort[portNum];
  }

  // ----------------------------------------------------------------------
  // Component construction and destruction
  // ----------------------------------------------------------------------

  AnalogDriverComponentBase ::
    AnalogDriverComponentBase(const char* compName) :
      Fw::PassiveComponentBase(compName)
  {

  }

  AnalogDriverComponentBase ::
    ~AnalogDriverComponentBase()
  {

  }

  // ----------------------------------------------------------------------
  // Getters for numbers of typed input ports
  // ----------------------------------------------------------------------

  FwIndexType AnalogDriverComponentBase ::
    getNum_readAnalog_InputPorts() const
  {
    return static_cast<FwIndexType>(FW_NUM_ARRAY_ELEMENTS(this->m_readAnalog_InputPort));
  }

  FwIndexType AnalogDriverComponentBase ::
    getNum_setAnalog_InputPorts() const
  {
    return static_cast<FwIndexType>(FW_NUM_ARRAY_ELEMENTS(this->m_setAnalog_InputPort));
  }

  // ----------------------------------------------------------------------
  // Port handler base-class functions for typed input ports
  //
  // Call these functions directly to bypass the corresponding ports
  // ----------------------------------------------------------------------

  Fw::Success AnalogDriverComponentBase ::
    readAnalog_handlerBase(
        FwIndexType portNum,
        U16& val
    )
  {
    // Make sure port number is valid
    FW_ASSERT(
      portNum < this->getNum_readAnalog_InputPorts(),
      static_cast<FwAssertArgType>(portNum)
    );

    Fw::Success retVal;

    // Call handler function
    retVal = this->readAnalog_handler(
      portNum,
      val
    );

    return retVal;
  }

  Fw::Success AnalogDriverComponentBase ::
    setAnalog_handlerBase(
        FwIndexType portNum,
        U8 val
    )
  {
    // Make sure port number is valid
    FW_ASSERT(
      portNum < this->getNum_setAnalog_InputPorts(),
      static_cast<FwAssertArgType>(portNum)
    );

    Fw::Success retVal;

    // Call handler function
    retVal = this->setAnalog_handler(
      portNum,
      val
    );

    return retVal;
  }

  // ----------------------------------------------------------------------
  // Calls for messages received on typed input ports
  // ----------------------------------------------------------------------

  Fw::Success AnalogDriverComponentBase ::
    m_p_readAnalog_in(
        Fw::PassiveComponentBase* callComp,
        FwIndexType portNum,
        U16& val
    )
  {
    FW_ASSERT(callComp);
    AnalogDriverComponentBase* compPtr = static_cast<AnalogDriverComponentBase*>(callComp);
    return compPtr->readAnalog_handlerBase(
      portNum,
      val
    );
  }

  Fw::Success AnalogDriverComponentBase ::
    m_p_setAnalog_in(
        Fw::PassiveComponentBase* callComp,
        FwIndexType portNum,
        U8 val
    )
  {
    FW_ASSERT(callComp);
    AnalogDriverComponentBase* compPtr = static_cast<AnalogDriverComponentBase*>(callComp);
    return compPtr->setAnalog_handlerBase(
      portNum,
      val
    );
  }

}
