// ======================================================================
// \title  AnalogWritePortAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for AnalogWrite port
// ======================================================================

#include "Arduino/Drv/AnalogDriver/AnalogWritePortAc.hpp"
#include "Fw/Types/Assert.hpp"
#include "Fw/Types/ExternalString.hpp"

namespace Drv {

  // ----------------------------------------------------------------------
  // Input Port Member functions
  // ----------------------------------------------------------------------

  InputAnalogWritePort ::
    InputAnalogWritePort() :
      Fw::InputPortBase(),
      m_func(nullptr)
  {

  }

  void InputAnalogWritePort ::
    init()
  {
    Fw::InputPortBase::init();
  }

  void InputAnalogWritePort ::
    addCallComp(
        Fw::PassiveComponentBase* callComp,
        CompFuncPtr funcPtr
    )
  {
    FW_ASSERT(callComp != nullptr);
    FW_ASSERT(funcPtr != nullptr);

    this->m_comp = callComp;
    this->m_func = funcPtr;
    this->m_connObj = callComp;
  }

  Fw::Success InputAnalogWritePort ::
    invoke(U8 val)
  {
#if FW_PORT_TRACING == 1
    this->trace();
#endif

    FW_ASSERT(this->m_comp != nullptr);
    FW_ASSERT(this->m_func != nullptr);

    return this->m_func(this->m_comp, this->m_portNum, val);
  }

#if FW_PORT_SERIALIZATION == 1

  Fw::SerializeStatus InputAnalogWritePort ::
    invokeSerial(Fw::SerializeBufferBase& _buffer)
  {
    // For ports with a return type, invokeSerial is not used
    (void) _buffer;

    FW_ASSERT(0);
    return Fw::FW_SERIALIZE_OK;
  }

#endif

  // ----------------------------------------------------------------------
  // Output Port Member functions
  // ----------------------------------------------------------------------

  OutputAnalogWritePort ::
    OutputAnalogWritePort() :
      Fw::OutputPortBase(),
      m_port(nullptr)
  {

  }

  void OutputAnalogWritePort ::
    init()
  {
    Fw::OutputPortBase::init();
  }

  void OutputAnalogWritePort ::
    addCallPort(InputAnalogWritePort* callPort)
  {
    FW_ASSERT(callPort != nullptr);

    this->m_port = callPort;
    this->m_connObj = callPort;

#if FW_PORT_SERIALIZATION == 1
    this->m_serPort = nullptr;
#endif
  }

  Fw::Success OutputAnalogWritePort ::
    invoke(U8 val) const
  {
#if FW_PORT_TRACING == 1
    this->trace();
#endif

    FW_ASSERT(this->m_port != nullptr);
    return this->m_port->invoke(val);
  }

}
