// ======================================================================
// \title  I2cDriverComponentAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for I2cDriver component base class
// ======================================================================

#include "Arduino/Drv/I2cDriver/I2cDriverComponentAc.hpp"
#include "Fw/Types/Assert.hpp"
#include "Fw/Types/ExternalString.hpp"
#if FW_ENABLE_TEXT_LOGGING
#include "Fw/Types/String.hpp"
#endif

namespace Arduino {

  // ----------------------------------------------------------------------
  // Component initialization
  // ----------------------------------------------------------------------

  void I2cDriverComponentBase ::
    init(FwEnumStoreType instance)
  {
    // Initialize base class
    Fw::PassiveComponentBase::init(instance);

    // Connect input port read
    for (
      FwIndexType port = 0;
      port < static_cast<FwIndexType>(this->getNum_read_InputPorts());
      port++
    ) {
      this->m_read_InputPort[port].init();
      this->m_read_InputPort[port].addCallComp(
        this,
        m_p_read_in
      );
      this->m_read_InputPort[port].setPortNum(port);

#if FW_OBJECT_NAMES == 1
      Fw::ObjectName portName;
      portName.format(
        "%s_read_InputPort[%" PRI_PlatformIntType "]",
        this->m_objName.toChar(),
        port
      );
      this->m_read_InputPort[port].setObjName(portName.toChar());
#endif
    }

    // Connect input port write
    for (
      FwIndexType port = 0;
      port < static_cast<FwIndexType>(this->getNum_write_InputPorts());
      port++
    ) {
      this->m_write_InputPort[port].init();
      this->m_write_InputPort[port].addCallComp(
        this,
        m_p_write_in
      );
      this->m_write_InputPort[port].setPortNum(port);

#if FW_OBJECT_NAMES == 1
      Fw::ObjectName portName;
      portName.format(
        "%s_write_InputPort[%" PRI_PlatformIntType "]",
        this->m_objName.toChar(),
        port
      );
      this->m_write_InputPort[port].setObjName(portName.toChar());
#endif
    }
  }

  // ----------------------------------------------------------------------
  // Getters for typed input ports
  // ----------------------------------------------------------------------

  Drv::InputI2cPort* I2cDriverComponentBase ::
    get_read_InputPort(FwIndexType portNum)
  {
    FW_ASSERT(
      portNum < this->getNum_read_InputPorts(),
      static_cast<FwAssertArgType>(portNum)
    );

    return &this->m_read_InputPort[portNum];
  }

  Drv::InputI2cPort* I2cDriverComponentBase ::
    get_write_InputPort(FwIndexType portNum)
  {
    FW_ASSERT(
      portNum < this->getNum_write_InputPorts(),
      static_cast<FwAssertArgType>(portNum)
    );

    return &this->m_write_InputPort[portNum];
  }

  // ----------------------------------------------------------------------
  // Component construction and destruction
  // ----------------------------------------------------------------------

  I2cDriverComponentBase ::
    I2cDriverComponentBase(const char* compName) :
      Fw::PassiveComponentBase(compName)
  {

  }

  I2cDriverComponentBase ::
    ~I2cDriverComponentBase()
  {

  }

  // ----------------------------------------------------------------------
  // Getters for numbers of typed input ports
  // ----------------------------------------------------------------------

  FwIndexType I2cDriverComponentBase ::
    getNum_read_InputPorts() const
  {
    return static_cast<FwIndexType>(FW_NUM_ARRAY_ELEMENTS(this->m_read_InputPort));
  }

  FwIndexType I2cDriverComponentBase ::
    getNum_write_InputPorts() const
  {
    return static_cast<FwIndexType>(FW_NUM_ARRAY_ELEMENTS(this->m_write_InputPort));
  }

  // ----------------------------------------------------------------------
  // Port handler base-class functions for typed input ports
  //
  // Call these functions directly to bypass the corresponding ports
  // ----------------------------------------------------------------------

  Drv::I2cStatus I2cDriverComponentBase ::
    read_handlerBase(
        FwIndexType portNum,
        U32 addr,
        Fw::Buffer& serBuffer
    )
  {
    // Make sure port number is valid
    FW_ASSERT(
      portNum < this->getNum_read_InputPorts(),
      static_cast<FwAssertArgType>(portNum)
    );

    Drv::I2cStatus retVal;

    // Lock guard mutex before calling
    this->lock();

    // Call handler function
    retVal = this->read_handler(
      portNum,
      addr,
      serBuffer
    );

    // Unlock guard mutex
    this->unLock();

    return retVal;
  }

  Drv::I2cStatus I2cDriverComponentBase ::
    write_handlerBase(
        FwIndexType portNum,
        U32 addr,
        Fw::Buffer& serBuffer
    )
  {
    // Make sure port number is valid
    FW_ASSERT(
      portNum < this->getNum_write_InputPorts(),
      static_cast<FwAssertArgType>(portNum)
    );

    Drv::I2cStatus retVal;

    // Lock guard mutex before calling
    this->lock();

    // Call handler function
    retVal = this->write_handler(
      portNum,
      addr,
      serBuffer
    );

    // Unlock guard mutex
    this->unLock();

    return retVal;
  }

  // ----------------------------------------------------------------------
  // Mutex operations for guarded ports
  //
  // You can override these operations to provide more sophisticated
  // synchronization
  // ----------------------------------------------------------------------

  void I2cDriverComponentBase ::
    lock()
  {
    this->m_guardedPortMutex.lock();
  }

  void I2cDriverComponentBase ::
    unLock()
  {
    this->m_guardedPortMutex.unLock();
  }

  // ----------------------------------------------------------------------
  // Calls for messages received on typed input ports
  // ----------------------------------------------------------------------

  Drv::I2cStatus I2cDriverComponentBase ::
    m_p_read_in(
        Fw::PassiveComponentBase* callComp,
        FwIndexType portNum,
        U32 addr,
        Fw::Buffer& serBuffer
    )
  {
    FW_ASSERT(callComp);
    I2cDriverComponentBase* compPtr = static_cast<I2cDriverComponentBase*>(callComp);
    return compPtr->read_handlerBase(
      portNum,
      addr,
      serBuffer
    );
  }

  Drv::I2cStatus I2cDriverComponentBase ::
    m_p_write_in(
        Fw::PassiveComponentBase* callComp,
        FwIndexType portNum,
        U32 addr,
        Fw::Buffer& serBuffer
    )
  {
    FW_ASSERT(callComp);
    I2cDriverComponentBase* compPtr = static_cast<I2cDriverComponentBase*>(callComp);
    return compPtr->write_handlerBase(
      portNum,
      addr,
      serBuffer
    );
  }

}
