// ======================================================================
// \title  SetTimePortAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for SetTime port
// ======================================================================

#ifndef Arduino_SetTimePortAc_HPP
#define Arduino_SetTimePortAc_HPP

#include <cstdio>
#include <cstring>

#include "FpConfig.hpp"
#include "Fw/Comp/PassiveComponentBase.hpp"
#include "Fw/Port/InputPortBase.hpp"
#include "Fw/Port/OutputPortBase.hpp"
#include "Fw/Types/Serializable.hpp"
#include "Fw/Types/StringType.hpp"

namespace Arduino {

  //! Input SetTime port
  //! Port allowing a component to set the time
  class InputSetTimePort :
    public Fw::InputPortBase
  {

    public:

      // ----------------------------------------------------------------------
      // Constants
      // ----------------------------------------------------------------------

      enum {
        //! The size of the serial representations of the port arguments
        SERIALIZED_SIZE =
          sizeof(U32) +
          sizeof(U8) +
          sizeof(U8) +
          sizeof(U8) +
          sizeof(U8) +
          sizeof(U8)
      };

    public:

      // ----------------------------------------------------------------------
      // Types
      // ----------------------------------------------------------------------

      //! The port callback function type
      typedef void (*CompFuncPtr)(
        Fw::PassiveComponentBase* callComp,
        FwIndexType portNum,
        U32 year,
        U8 month,
        U8 day,
        U8 hour,
        U8 minute,
        U8 second
      );

    public:

      // ----------------------------------------------------------------------
      // Input Port Member functions
      // ----------------------------------------------------------------------

      //! Constructor
      InputSetTimePort();

      //! Initialization function
      void init();

      //! Register a component
      void addCallComp(
          Fw::PassiveComponentBase* callComp, //!< The containing component
          CompFuncPtr funcPtr //!< The port callback function
      );

      //! Invoke a port interface
      void invoke(
          U32 year, //!< The current year
          U8 month, //!< The current month (1-12)
          U8 day, //!< The current day (1-31)
          U8 hour, //!< The current hour (0-23)
          U8 minute, //!< The current minute (0-59)
          U8 second //!< The current second (0-59)
      );

    private:

#if FW_PORT_SERIALIZATION == 1

      //! Invoke the port with serialized arguments
      Fw::SerializeStatus invokeSerial(Fw::SerializeBufferBase& _buffer);

#endif

    private:

      // ----------------------------------------------------------------------
      // Member variables
      // ----------------------------------------------------------------------

      //! The pointer to the port callback function
      CompFuncPtr m_func;

  };

  //! Output SetTime port
  //! Port allowing a component to set the time
  class OutputSetTimePort :
    public Fw::OutputPortBase
  {

    public:

      // ----------------------------------------------------------------------
      // Output Port Member functions
      // ----------------------------------------------------------------------

      //! Constructor
      OutputSetTimePort();

      //! Initialization function
      void init();

      //! Register an input port
      void addCallPort(
          InputSetTimePort* callPort //!< The input port
      );

      //! Invoke a port interface
      void invoke(
          U32 year, //!< The current year
          U8 month, //!< The current month (1-12)
          U8 day, //!< The current day (1-31)
          U8 hour, //!< The current hour (0-23)
          U8 minute, //!< The current minute (0-59)
          U8 second //!< The current second (0-59)
      ) const;

    private:

      // ----------------------------------------------------------------------
      // Member variables
      // ----------------------------------------------------------------------

      //! The pointer to the input port
      InputSetTimePort* m_port;

  };

}

#endif
