// ======================================================================
// \title  SetTimePortAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for SetTime port
// ======================================================================

#include "Arduino/Svc/Ports/SetTimePortAc.hpp"
#include "Fw/Types/Assert.hpp"
#include "Fw/Types/ExternalString.hpp"

namespace Arduino {

  namespace {

    // ----------------------------------------------------------------------
    // Port buffer class
    // ----------------------------------------------------------------------

    class SetTimePortBuffer : public Fw::SerializeBufferBase {

      public:

        Fw::Serializable::SizeType getBuffCapacity() const {
          return InputSetTimePort::SERIALIZED_SIZE;
        }

        U8* getBuffAddr() {
          return m_buff;
        }

        const U8* getBuffAddr() const {
          return m_buff;
        }

      private:

        U8 m_buff[InputSetTimePort::SERIALIZED_SIZE];

    };

  }

  // ----------------------------------------------------------------------
  // Input Port Member functions
  // ----------------------------------------------------------------------

  InputSetTimePort ::
    InputSetTimePort() :
      Fw::InputPortBase(),
      m_func(nullptr)
  {

  }

  void InputSetTimePort ::
    init()
  {
    Fw::InputPortBase::init();
  }

  void InputSetTimePort ::
    addCallComp(
        Fw::PassiveComponentBase* callComp,
        CompFuncPtr funcPtr
    )
  {
    FW_ASSERT(callComp != nullptr);
    FW_ASSERT(funcPtr != nullptr);

    this->m_comp = callComp;
    this->m_func = funcPtr;
    this->m_connObj = callComp;
  }

  void InputSetTimePort ::
    invoke(
        U32 year,
        U8 month,
        U8 day,
        U8 hour,
        U8 minute,
        U8 second
    )
  {
#if FW_PORT_TRACING == 1
    this->trace();
#endif

    FW_ASSERT(this->m_comp != nullptr);
    FW_ASSERT(this->m_func != nullptr);

    return this->m_func(this->m_comp, this->m_portNum, year, month, day, hour, minute, second);
  }

#if FW_PORT_SERIALIZATION == 1

  Fw::SerializeStatus InputSetTimePort ::
    invokeSerial(Fw::SerializeBufferBase& _buffer)
  {
    Fw::SerializeStatus _status;

#if FW_PORT_TRACING == 1
    this->trace();
#endif

    FW_ASSERT(this->m_comp != nullptr);
    FW_ASSERT(this->m_func != nullptr);

    U32 year;
    _status = _buffer.deserialize(year);
    if (_status != Fw::FW_SERIALIZE_OK) {
      return _status;
    }

    U8 month;
    _status = _buffer.deserialize(month);
    if (_status != Fw::FW_SERIALIZE_OK) {
      return _status;
    }

    U8 day;
    _status = _buffer.deserialize(day);
    if (_status != Fw::FW_SERIALIZE_OK) {
      return _status;
    }

    U8 hour;
    _status = _buffer.deserialize(hour);
    if (_status != Fw::FW_SERIALIZE_OK) {
      return _status;
    }

    U8 minute;
    _status = _buffer.deserialize(minute);
    if (_status != Fw::FW_SERIALIZE_OK) {
      return _status;
    }

    U8 second;
    _status = _buffer.deserialize(second);
    if (_status != Fw::FW_SERIALIZE_OK) {
      return _status;
    }

    this->m_func(this->m_comp, this->m_portNum, year, month, day, hour, minute, second);

    return Fw::FW_SERIALIZE_OK;
  }

#endif

  // ----------------------------------------------------------------------
  // Output Port Member functions
  // ----------------------------------------------------------------------

  OutputSetTimePort ::
    OutputSetTimePort() :
      Fw::OutputPortBase(),
      m_port(nullptr)
  {

  }

  void OutputSetTimePort ::
    init()
  {
    Fw::OutputPortBase::init();
  }

  void OutputSetTimePort ::
    addCallPort(InputSetTimePort* callPort)
  {
    FW_ASSERT(callPort != nullptr);

    this->m_port = callPort;
    this->m_connObj = callPort;

#if FW_PORT_SERIALIZATION == 1
    this->m_serPort = nullptr;
#endif
  }

  void OutputSetTimePort ::
    invoke(
        U32 year,
        U8 month,
        U8 day,
        U8 hour,
        U8 minute,
        U8 second
    ) const
  {
#if FW_PORT_TRACING == 1
    this->trace();
#endif

#if FW_PORT_SERIALIZATION
    FW_ASSERT((this->m_port != nullptr) || (this->m_serPort != nullptr));

    if (this->m_port != nullptr) {
      this->m_port->invoke(year, month, day, hour, minute, second);
    }
    else {
      Fw::SerializeStatus _status;
      SetTimePortBuffer _buffer;

      _status = _buffer.serialize(year);
      FW_ASSERT(_status == Fw::FW_SERIALIZE_OK, static_cast<FwAssertArgType>(_status));

      _status = _buffer.serialize(month);
      FW_ASSERT(_status == Fw::FW_SERIALIZE_OK, static_cast<FwAssertArgType>(_status));

      _status = _buffer.serialize(day);
      FW_ASSERT(_status == Fw::FW_SERIALIZE_OK, static_cast<FwAssertArgType>(_status));

      _status = _buffer.serialize(hour);
      FW_ASSERT(_status == Fw::FW_SERIALIZE_OK, static_cast<FwAssertArgType>(_status));

      _status = _buffer.serialize(minute);
      FW_ASSERT(_status == Fw::FW_SERIALIZE_OK, static_cast<FwAssertArgType>(_status));

      _status = _buffer.serialize(second);
      FW_ASSERT(_status == Fw::FW_SERIALIZE_OK, static_cast<FwAssertArgType>(_status));

      _status = this->m_serPort->invokeSerial(_buffer);
      FW_ASSERT(_status == Fw::FW_SERIALIZE_OK, static_cast<FwAssertArgType>(_status));
    }
#else
    FW_ASSERT(this->m_port != nullptr);
    this->m_port->invoke(year, month, day, hour, minute, second);
#endif
  }

}
