// ======================================================================
// \title  SpiDriverComponentAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for SpiDriver component base class
// ======================================================================

#include "Arduino/Drv/SpiDriver/SpiDriverComponentAc.hpp"
#include "Fw/Types/Assert.hpp"
#include "Fw/Types/ExternalString.hpp"
#if FW_ENABLE_TEXT_LOGGING
#include "Fw/Types/String.hpp"
#endif

namespace Arduino {

  // ----------------------------------------------------------------------
  // Component initialization
  // ----------------------------------------------------------------------

  void SpiDriverComponentBase ::
    init(FwEnumStoreType instance)
  {
    // Initialize base class
    Fw::PassiveComponentBase::init(instance);

    // Connect input port SpiReadWrite
    for (
      FwIndexType port = 0;
      port < static_cast<FwIndexType>(this->getNum_SpiReadWrite_InputPorts());
      port++
    ) {
      this->m_SpiReadWrite_InputPort[port].init();
      this->m_SpiReadWrite_InputPort[port].addCallComp(
        this,
        m_p_SpiReadWrite_in
      );
      this->m_SpiReadWrite_InputPort[port].setPortNum(port);

#if FW_OBJECT_NAMES == 1
      Fw::ObjectName portName;
      portName.format(
        "%s_SpiReadWrite_InputPort[%" PRI_PlatformIntType "]",
        this->m_objName.toChar(),
        port
      );
      this->m_SpiReadWrite_InputPort[port].setObjName(portName.toChar());
#endif
    }
  }

  // ----------------------------------------------------------------------
  // Getters for typed input ports
  // ----------------------------------------------------------------------

  Drv::InputSpiReadWritePort* SpiDriverComponentBase ::
    get_SpiReadWrite_InputPort(FwIndexType portNum)
  {
    FW_ASSERT(
      portNum < this->getNum_SpiReadWrite_InputPorts(),
      static_cast<FwAssertArgType>(portNum)
    );

    return &this->m_SpiReadWrite_InputPort[portNum];
  }

  // ----------------------------------------------------------------------
  // Component construction and destruction
  // ----------------------------------------------------------------------

  SpiDriverComponentBase ::
    SpiDriverComponentBase(const char* compName) :
      Fw::PassiveComponentBase(compName)
  {

  }

  SpiDriverComponentBase ::
    ~SpiDriverComponentBase()
  {

  }

  // ----------------------------------------------------------------------
  // Getters for numbers of typed input ports
  // ----------------------------------------------------------------------

  FwIndexType SpiDriverComponentBase ::
    getNum_SpiReadWrite_InputPorts() const
  {
    return static_cast<FwIndexType>(FW_NUM_ARRAY_ELEMENTS(this->m_SpiReadWrite_InputPort));
  }

  // ----------------------------------------------------------------------
  // Port handler base-class functions for typed input ports
  //
  // Call these functions directly to bypass the corresponding ports
  // ----------------------------------------------------------------------

  void SpiDriverComponentBase ::
    SpiReadWrite_handlerBase(
        FwIndexType portNum,
        Fw::Buffer& writeBuffer,
        Fw::Buffer& readBuffer
    )
  {
    // Make sure port number is valid
    FW_ASSERT(
      portNum < this->getNum_SpiReadWrite_InputPorts(),
      static_cast<FwAssertArgType>(portNum)
    );

    // Call handler function
    this->SpiReadWrite_handler(
      portNum,
      writeBuffer,
      readBuffer
    );
  }

  // ----------------------------------------------------------------------
  // Calls for messages received on typed input ports
  // ----------------------------------------------------------------------

  void SpiDriverComponentBase ::
    m_p_SpiReadWrite_in(
        Fw::PassiveComponentBase* callComp,
        FwIndexType portNum,
        Fw::Buffer& writeBuffer,
        Fw::Buffer& readBuffer
    )
  {
    FW_ASSERT(callComp);
    SpiDriverComponentBase* compPtr = static_cast<SpiDriverComponentBase*>(callComp);
    compPtr->SpiReadWrite_handlerBase(
      portNum,
      writeBuffer,
      readBuffer
    );
  }

}
