// ======================================================================
// \title  DutyCyclePortAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for DutyCycle port
// ======================================================================

#include "Arduino/Drv/PwmDriver/DutyCyclePortAc.hpp"
#include "Fw/Types/Assert.hpp"
#include "Fw/Types/ExternalString.hpp"

namespace Drv {

  // ----------------------------------------------------------------------
  // Input Port Member functions
  // ----------------------------------------------------------------------

  InputDutyCyclePort ::
    InputDutyCyclePort() :
      Fw::InputPortBase(),
      m_func(nullptr)
  {

  }

  void InputDutyCyclePort ::
    init()
  {
    Fw::InputPortBase::init();
  }

  void InputDutyCyclePort ::
    addCallComp(
        Fw::PassiveComponentBase* callComp,
        CompFuncPtr funcPtr
    )
  {
    FW_ASSERT(callComp != nullptr);
    FW_ASSERT(funcPtr != nullptr);

    this->m_comp = callComp;
    this->m_func = funcPtr;
    this->m_connObj = callComp;
  }

  Fw::Success InputDutyCyclePort ::
    invoke(U8 dutyCycle)
  {
#if FW_PORT_TRACING == 1
    this->trace();
#endif

    FW_ASSERT(this->m_comp != nullptr);
    FW_ASSERT(this->m_func != nullptr);

    return this->m_func(this->m_comp, this->m_portNum, dutyCycle);
  }

#if FW_PORT_SERIALIZATION == 1

  Fw::SerializeStatus InputDutyCyclePort ::
    invokeSerial(Fw::SerializeBufferBase& _buffer)
  {
    // For ports with a return type, invokeSerial is not used
    (void) _buffer;

    FW_ASSERT(0);
    return Fw::FW_SERIALIZE_OK;
  }

#endif

  // ----------------------------------------------------------------------
  // Output Port Member functions
  // ----------------------------------------------------------------------

  OutputDutyCyclePort ::
    OutputDutyCyclePort() :
      Fw::OutputPortBase(),
      m_port(nullptr)
  {

  }

  void OutputDutyCyclePort ::
    init()
  {
    Fw::OutputPortBase::init();
  }

  void OutputDutyCyclePort ::
    addCallPort(InputDutyCyclePort* callPort)
  {
    FW_ASSERT(callPort != nullptr);

    this->m_port = callPort;
    this->m_connObj = callPort;

#if FW_PORT_SERIALIZATION == 1
    this->m_serPort = nullptr;
#endif
  }

  Fw::Success OutputDutyCyclePort ::
    invoke(U8 dutyCycle) const
  {
#if FW_PORT_TRACING == 1
    this->trace();
#endif

    FW_ASSERT(this->m_port != nullptr);
    return this->m_port->invoke(dutyCycle);
  }

}
