// ======================================================================
// \title  PwmDriverComponentAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for PwmDriver component base class
// ======================================================================

#include "Arduino/Drv/PwmDriver/PwmDriverComponentAc.hpp"
#include "Fw/Types/Assert.hpp"
#include "Fw/Types/ExternalString.hpp"
#if FW_ENABLE_TEXT_LOGGING
#include "Fw/Types/String.hpp"
#endif

namespace Arduino {

  // ----------------------------------------------------------------------
  // Component initialization
  // ----------------------------------------------------------------------

  void PwmDriverComponentBase ::
    init(FwEnumStoreType instance)
  {
    // Initialize base class
    Fw::PassiveComponentBase::init(instance);

    // Connect input port setDutyCycle
    for (
      FwIndexType port = 0;
      port < static_cast<FwIndexType>(this->getNum_setDutyCycle_InputPorts());
      port++
    ) {
      this->m_setDutyCycle_InputPort[port].init();
      this->m_setDutyCycle_InputPort[port].addCallComp(
        this,
        m_p_setDutyCycle_in
      );
      this->m_setDutyCycle_InputPort[port].setPortNum(port);

#if FW_OBJECT_NAMES == 1
      Fw::ObjectName portName;
      portName.format(
        "%s_setDutyCycle_InputPort[%" PRI_PlatformIntType "]",
        this->m_objName.toChar(),
        port
      );
      this->m_setDutyCycle_InputPort[port].setObjName(portName.toChar());
#endif
    }
  }

  // ----------------------------------------------------------------------
  // Getters for typed input ports
  // ----------------------------------------------------------------------

  Drv::InputDutyCyclePort* PwmDriverComponentBase ::
    get_setDutyCycle_InputPort(FwIndexType portNum)
  {
    FW_ASSERT(
      portNum < this->getNum_setDutyCycle_InputPorts(),
      static_cast<FwAssertArgType>(portNum)
    );

    return &this->m_setDutyCycle_InputPort[portNum];
  }

  // ----------------------------------------------------------------------
  // Component construction and destruction
  // ----------------------------------------------------------------------

  PwmDriverComponentBase ::
    PwmDriverComponentBase(const char* compName) :
      Fw::PassiveComponentBase(compName)
  {

  }

  PwmDriverComponentBase ::
    ~PwmDriverComponentBase()
  {

  }

  // ----------------------------------------------------------------------
  // Getters for numbers of typed input ports
  // ----------------------------------------------------------------------

  FwIndexType PwmDriverComponentBase ::
    getNum_setDutyCycle_InputPorts() const
  {
    return static_cast<FwIndexType>(FW_NUM_ARRAY_ELEMENTS(this->m_setDutyCycle_InputPort));
  }

  // ----------------------------------------------------------------------
  // Port handler base-class functions for typed input ports
  //
  // Call these functions directly to bypass the corresponding ports
  // ----------------------------------------------------------------------

  Fw::Success PwmDriverComponentBase ::
    setDutyCycle_handlerBase(
        FwIndexType portNum,
        U8 dutyCycle
    )
  {
    // Make sure port number is valid
    FW_ASSERT(
      portNum < this->getNum_setDutyCycle_InputPorts(),
      static_cast<FwAssertArgType>(portNum)
    );

    Fw::Success retVal;

    // Call handler function
    retVal = this->setDutyCycle_handler(
      portNum,
      dutyCycle
    );

    return retVal;
  }

  // ----------------------------------------------------------------------
  // Calls for messages received on typed input ports
  // ----------------------------------------------------------------------

  Fw::Success PwmDriverComponentBase ::
    m_p_setDutyCycle_in(
        Fw::PassiveComponentBase* callComp,
        FwIndexType portNum,
        U8 dutyCycle
    )
  {
    FW_ASSERT(callComp);
    PwmDriverComponentBase* compPtr = static_cast<PwmDriverComponentBase*>(callComp);
    return compPtr->setDutyCycle_handlerBase(
      portNum,
      dutyCycle
    );
  }

}
